// SPDX-License-Identifier: MIT
/**
 * Blueprint for the background messaging subtree.
 *
 * Object literals are inlined so `scripts/validate-blueprints.ts` can walk the
 * array statically and cross-check every `key: '...'` against ProtocolMap.
 */

import type { ModuleBlueprint } from '../../_blueprints/blueprint.types';

export const blueprint: ModuleBlueprint = {
  moduleId: 'background/messaging',
  label: 'Background Messaging Surface',
  description:
    'Single API surface between content, background, popup, sidepanel, options. ' +
    'All ProtocolMap keys routed through typed sendMessage/onMessage. Every handler ' +
    'validates its payload with Zod before business logic. Broadcast-only keys ' +
    'register inert handlers so the exhaustive HANDLERS record type-checks.',
  category: 'messaging',
  publicExports: [
    'ProtocolMap',
    'BG_HANDLED_KEYS',
    'ALL_PROTOCOL_KEYS',
    'sendMessage',
    'onMessage',
    'registerHandlers',
    'createHandlers',
  ],
  forbiddenImports: [
    'entrypoints/popup',
    'entrypoints/sidepanel',
    'entrypoints/options',
  ],
  messageHandlers: [
    {
      key: 'AUTH_SIGN_IN',
      description: 'Exchange LLMConveyors session cookie for extension token',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/auth.schema',
      responseSchemaRef: './schemas/auth.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'AUTH_SIGN_OUT',
      description: 'Clear session, broadcast state change',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/auth.schema',
      responseSchemaRef: './schemas/auth.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'AUTH_STATUS',
      description: 'Return current AuthState',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/auth.schema',
      responseSchemaRef: './schemas/auth.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'AUTH_STATE_CHANGED',
      description: 'Broadcast on sign-in/out (inert bg handler)',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/auth.schema',
      responseSchemaRef: './schemas/auth.schema',
      broadcastOnly: true,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'INTENT_DETECTED',
      description: 'Content reports detected page intent',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/intent.schema',
      responseSchemaRef: './schemas/intent.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'INTENT_GET',
      description: 'Read cached intent for a tab',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/intent.schema',
      responseSchemaRef: './schemas/intent.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'FILL_REQUEST',
      description: 'Popup requests autofill; bg forwards to content',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/fill.schema',
      responseSchemaRef: './schemas/fill.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'KEYWORDS_EXTRACT',
      description: 'Extract job keywords via backend API',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/keywords.schema',
      responseSchemaRef: './schemas/keywords.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'HIGHLIGHT_APPLY',
      description: 'Apply keyword highlights to page (content-side)',
      handlerLocation: 'content',
      requestSchemaRef: './schemas/highlight.schema',
      responseSchemaRef: './schemas/highlight.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'HIGHLIGHT_CLEAR',
      description: 'Clear all highlights on page (content-side)',
      handlerLocation: 'content',
      requestSchemaRef: './schemas/highlight.schema',
      responseSchemaRef: './schemas/highlight.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'HIGHLIGHT_STATUS',
      description: 'Report highlight state for a tab',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/highlight.schema',
      responseSchemaRef: './schemas/highlight.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_START',
      description: 'Trigger agent generation via backend',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_UPDATE',
      description: 'Broadcast generation progress (inert handler)',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: true,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_CANCEL',
      description: 'Cancel an in-flight generation',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'DETECTED_JOB_BROADCAST',
      description: 'Fan out detected job to all listeners',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/intent.schema',
      responseSchemaRef: './schemas/intent.schema',
      broadcastOnly: true,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'CREDITS_GET',
      description: 'Read credits balance from backend',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/credits.schema',
      responseSchemaRef: './schemas/credits.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'PROFILE_GET',
      description: 'Read profile identity (email, displayName, photoURL) from backend',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/profile.schema',
      responseSchemaRef: './schemas/profile.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_SUBSCRIBE',
      description: 'Open a fetch-based SSE stream for live generation updates',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_INTERACT',
      description: 'User response to an in-flight interaction-request',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_STARTED',
      description: 'Broadcast that a new generation has started',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: true,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'GENERATION_COMPLETE',
      description: 'Broadcast that a generation has finished (invalidates session cache)',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generation.schema',
      responseSchemaRef: './schemas/generation.schema',
      broadcastOnly: true,
      invariants: [],
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
    {
      key: 'MASTER_RESUME_GET',
      description: 'Read backend master resume with cache fallback',
      handlerLocation: 'background',
      requestSchemaRef: '../master-resume/index',
      responseSchemaRef: '../master-resume/index',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../master-resume/index.ts', line: 1 },
    },
    {
      key: 'MASTER_RESUME_PUT',
      description: 'Upsert backend master resume',
      handlerLocation: 'background',
      requestSchemaRef: '../master-resume/index',
      responseSchemaRef: '../master-resume/index',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../master-resume/index.ts', line: 1 },
    },
    {
      key: 'AGENT_PREFERENCE_GET',
      description: 'Read the user-preferred agent id',
      handlerLocation: 'background',
      requestSchemaRef: '../agents/agent-handlers',
      responseSchemaRef: '../agents/agent-handlers',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../agents/index.ts', line: 1 },
    },
    {
      key: 'AGENT_PREFERENCE_SET',
      description: 'Persist the user-preferred agent id',
      handlerLocation: 'background',
      requestSchemaRef: '../agents/agent-handlers',
      responseSchemaRef: '../agents/agent-handlers',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../agents/index.ts', line: 1 },
    },
    {
      key: 'AGENT_REGISTRY_LIST',
      description: 'Return the frozen AGENT_REGISTRY to popup / sidepanel',
      handlerLocation: 'background',
      requestSchemaRef: '../agents/agent-handlers',
      responseSchemaRef: '../agents/agent-handlers',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../agents/index.ts', line: 1 },
    },
    {
      key: 'AGENT_MANIFEST_GET',
      description: 'Fetch the backend agent manifest with shape validation',
      handlerLocation: 'background',
      requestSchemaRef: '../agents/agent-handlers',
      responseSchemaRef: '../agents/agent-handlers',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../agents/index.ts', line: 1 },
    },
    {
      key: 'SESSION_LIST',
      description: 'List user sessions via cached backend call',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/session-list.schema',
      responseSchemaRef: './schemas/session-list.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../sessions/session-handlers.ts', line: 1 },
    },
    {
      key: 'SESSION_GET',
      description: 'Fetch a single session, preferring the cache',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/session-list.schema',
      responseSchemaRef: './schemas/session-list.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../sessions/session-handlers.ts', line: 1 },
    },
    {
      key: 'GENERIC_INTENT_DETECT',
      description: 'Run a one-shot scan on the active tab when no adapter matches',
      handlerLocation: 'background',
      requestSchemaRef: './schemas/generic-intent.schema',
      responseSchemaRef: './schemas/generic-intent.schema',
      broadcastOnly: false,
      invariants: [],
      sourceRef: { file: '../generic-intent/generic-intent-handler.ts', line: 1 },
    },
  ],
  invariants: [
    {
      id: 'MESSAGING-001',
      description: 'Every ProtocolMap key has exactly one handler registration',
      severity: 'error',
      check: { type: 'custom', description: 'validator Layer 3 cross-check' },
      sourceRef: { file: 'protocol.ts', line: 1 },
    },
    {
      id: 'MESSAGING-002',
      description: 'Every handler validates input via Zod before business logic',
      severity: 'error',
      check: { type: 'custom', description: 'manual review + unit tests' },
      sourceRef: { file: 'handlers.ts', line: 1 },
    },
  ],
  knownIssues: [],
};
